name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Trigger workflow only when you push a tag starting with 'v'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest] # Add 'macos-latest' or 'ubuntu-latest' if you want Mac/Linux builds too

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the built-in token
        run: npm run build -- --publish always
